ALTER TABLE BOT
  ADD CONSTRAINT FK_BOTSKILL
  FOREIGN KEY (SkillID) REFERENCES SKILL (SkillID);

ALTER TABLE ITEM
  ADD CONSTRAINT FK_ITEMSKILL
  FOREIGN KEY (SkillID) REFERENCES SKILL (SkillID);
